# Generated by Django 2.0.5 on 2020-01-01 21:28

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DHandlowiec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', phone_field.models.PhoneField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('nazwa', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ulica', models.CharField(max_length=200)),
                ('miejscowosc', models.CharField(max_length=200)),
                ('kod_pocztowy', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Phandlowy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', phone_field.models.PhoneField(max_length=31)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwentarz.Firma')),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('numer_seryjny', models.IntegerField(primary_key=True, serialize=False)),
                ('licencja_car', models.BooleanField(default=True)),
                ('licencja_hd', models.BooleanField(default=True)),
                ('wypozyczony', models.BooleanField(default=True)),
                ('data_wypozyczenia', models.DateField(blank=True)),
                ('problemy', models.CharField(default='Brak problemów', max_length=2000)),
                ('dhandlowiec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inwentarz.DHandlowiec')),
                ('phandlowy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inwentarz.Phandlowy')),
            ],
        ),
    ]
