# Generated by Django 2.0.5 on 2020-01-03 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inwentarz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhandlowiec',
            name='firma',
            field=models.ForeignKey(default='Delphi', on_delete=django.db.models.deletion.CASCADE, to='inwentarz.Firma'),
        ),
        migrations.AlterField(
            model_name='dhandlowiec',
            name='telefon',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='phandlowy',
            name='telefon',
            field=models.IntegerField(),
        ),
    ]
