# Generated by Django 2.0.5 on 2020-01-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwentarz', '0002_auto_20200103_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dhandlowiec',
            options={'verbose_name_plural': 'Siły sprzdażowe - Delphi'},
        ),
        migrations.AlterModelOptions(
            name='firma',
            options={'verbose_name_plural': 'Klienci'},
        ),
        migrations.AlterModelOptions(
            name='phandlowy',
            options={'verbose_name_plural': 'Siły sprzdażowe - Klient'},
        ),
        migrations.AlterModelOptions(
            name='tester',
            options={'verbose_name_plural': 'Testery diagnostyczne'},
        ),
        migrations.AlterField(
            model_name='tester',
            name='data_wypozyczenia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
