# Generated by Django 3.0.2 on 2020-02-27 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DHandlowiec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Siły sprzdażowe - Delphi',
            },
        ),
        migrations.CreateModel(
            name='Filia',
            fields=[
                ('nazwa', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ulica', models.CharField(max_length=200)),
                ('miejscowosc', models.CharField(max_length=200)),
                ('kod_pocztowy', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('nazwa', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ulica', models.CharField(max_length=200)),
                ('miejscowosc', models.CharField(max_length=200)),
                ('kod_pocztowy', models.CharField(max_length=200)),
                ('dhandlowiec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwentarz.DHandlowiec')),
            ],
            options={
                'verbose_name_plural': 'Klienci',
            },
        ),
        migrations.CreateModel(
            name='Phandlowy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.IntegerField()),
                ('filia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwentarz.Filia')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwentarz.Firma')),
            ],
            options={
                'verbose_name_plural': 'Siły sprzdażowe - Klient',
            },
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('numer_seryjny', models.IntegerField(primary_key=True, serialize=False)),
                ('licencja_car', models.BooleanField(default=True)),
                ('licencja_hd', models.BooleanField(default=True)),
                ('wypozyczony', models.BooleanField(default=True)),
                ('data_wypozyczenia', models.DateField(blank=True, null=True)),
                ('problemy', models.CharField(default='Brak problemów', max_length=2000)),
                ('dhandlowiec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inwentarz.DHandlowiec')),
                ('phandlowy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inwentarz.Phandlowy')),
            ],
            options={
                'verbose_name_plural': 'Testery diagnostyczne',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTester',
            fields=[
                ('numer_seryjny', models.IntegerField(db_index=True)),
                ('licencja_car', models.BooleanField(default=True)),
                ('licencja_hd', models.BooleanField(default=True)),
                ('wypozyczony', models.BooleanField(default=True)),
                ('data_wypozyczenia', models.DateField(blank=True, null=True)),
                ('problemy', models.CharField(default='Brak problemów', max_length=2000)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dhandlowiec', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inwentarz.DHandlowiec')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('phandlowy', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inwentarz.Phandlowy')),
            ],
            options={
                'verbose_name': 'historical tester',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPhandlowy',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('filia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inwentarz.Filia')),
                ('firma', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inwentarz.Firma')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical phandlowy',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFirma',
            fields=[
                ('nazwa', models.CharField(db_index=True, max_length=200)),
                ('ulica', models.CharField(max_length=200)),
                ('miejscowosc', models.CharField(max_length=200)),
                ('kod_pocztowy', models.CharField(max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dhandlowiec', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inwentarz.DHandlowiec')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical firma',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFilia',
            fields=[
                ('nazwa', models.CharField(db_index=True, max_length=200)),
                ('ulica', models.CharField(max_length=200)),
                ('miejscowosc', models.CharField(max_length=200)),
                ('kod_pocztowy', models.CharField(max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('firma', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inwentarz.Firma')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical filia',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDHandlowiec',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical d handlowiec',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='filia',
            name='firma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inwentarz.Firma'),
        ),
    ]
